# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ifarm' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RATreeView'
  pod 'OEANotification'
  pod 'Alamofire', '~> 3.4'
  pod 'AlamofireImage', '~> 2.0'
  pod 'SwiftyJSON', '~> 2.3'
  pod 'KeychainAccess', '~> 2.3'
  pod 'Charts'
  pod 'NVActivityIndicatorView'
  pod 'IQKeyboardManagerSwift', '4.0.3'
  pod 'ESPullToRefresh'
end
